### ISSUE TITLE
Ordered list of rst is not rendered in a correct way

### ISSUE THREAD

**Issue by yungyuc** [sciwork/swportal#128]
See the example at #127.  A rst ordered list is not rendered correctly:

```rst
#. `Intel Xeon Platinum 9282
   <https://en.wikichip.org/wiki/intel/xeon_platinum/9282>`__

   #. 56 cores
   #. 77MB L3 cache memory

#. `AMD EPYC 7H12
   <https://www.amd.com/en/products/cpu/amd-epyc-7h12>`__

   #. 64 cores
   #. 256MB L3 cache memory
```

**Comment by ezio-melotti** [comment]
The problem is in `main.css`.
At line 357
```css
ol, ul {
  list-style: none;
  margin: 0;
  padding: 0;
}
```

and 654:
```css
li {
   list-style-position: outside;
   list-style-type: disc;
}
```

The latter sets the `li` type to `disc`, even for `ol`s.  If that's removed, the former removes the bullet/number altogether, so it should probably be changed to something like:
```css
li {
   list-style-position: outside;
}
ul li {
   list-style-type: disc;
}
ol li {
   list-style-type: decimal;
}
```
Note that these should already be the defaults, so removing both `list-style-type` rules from `main.css` might also fix the problem.

7582b0d701bf130ea62bfa9c327ec1f0f007f8c0 might be related, however `main.css` appears to be 2.54MB (why is it so big?) and can't be displayed in GitHub, so I can't check the `blame`.
